# 地图x方向长度
length_in_x: 2.5
# 地图y方向长度
length_in_y: 2.5
position_x: 0.0
position_y: 0.0
# 地图分辨率
resolution: 0.05
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
