# 地图x方向长度
length_in_x: 10.0
# 地图y方向长度
length_in_y: 10.0
position_x: 0
position_y: 0
# 地图分辨率
resolution: 0.1
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
# 地图刷新频率（在动态 物体清除时有用）
visibility_cleanup_rate: 10.0
scanning_duration: 0.1
fused_map_publishing_rate: 10.0
